const fs=require('fs'), vm=require('vm'), crypto=require('crypto');
let js=fs.readFileSync('Drupal studio.html','utf8').split('<script >')[1].split('</script>')[0].replace(/mount\(document\.getElementById\('app'\)\);\s*$/,'');
const store={}; const doc={querySelectorAll(){return[]}, getElementById(){return {innerHTML:'', style:{}, addEventListener(){}, click(){}}}, createElement(){return {}}};
const sandbox={console, TextEncoder, Blob, File, crypto:crypto.webcrypto, setInterval(){}, setTimeout, navigator:{clipboard:{writeText(){}}}, localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v}, document:doc};
vm.createContext(sandbox); vm.runInContext(js,sandbox);
vm.runInContext(`
function file(name,obj){ return new File([typeof obj==='string'?obj:JSON.stringify(obj)], name, {type:'application/json', lastModified: Date.now()}); }
function course(id='id1', title='Parcours 16 17 départemental'){return {id,title,typeCandidature:'Candidature individuelle',effectif:'12',presentiel:'3',distanciel:'2',dureeTotale:'5',niveauDeploiement:'Départemental',meta:{objectif:'Objectif IA IPR',contenu:'Contenu Sofia-FMO test@example.fr',prerequis:'Prerequis',publicConcerne:'Public',contact:'Contact'}}}
(async()=>{ ws=createWorkspace(); ws.currentWorkflow=WORKFLOWS.create; await importOvpFiles([file('ovp.json',{plan:{title:'Plan',courses:[course()]}})]); ensureCreationWorkspace(); const p=ws.pages[0]; ws.creation.drupal.theme=THEMES[0]; ws.creation.drupal.defaultDates={preinscriptionStartDate:'01/09/2026',unpublishDate:'30/09/2026'}; ws.creation.drupal.publics=[...DEFAULT_SELECTED_PUBLIC_IDS]; ws.creation.associations[p.canonicalId]={status:'validated',locked:true,dispositifCode:'D1',dispositifLabel:'Disp',modules:[{moduleCode:'M1',moduleLabel:'Mod',territoireCode:'16',territoireLabel:'Charente',preinscription:{link:'https://x.test'}}]}; ws.creation.departmentSelections[p.canonicalId]=['16','17']; ws.creation.duplicationModes[p.canonicalId]='bi'; ws.creation.edits[p.canonicalId]={accessibility:''}; const vars=getDrupalExportVariants(); if(vars.length!==1||vars[0].key!=='ovp:id1__bidept_16_17') throw Error('variants bi'); const item=buildDrupalCreateItem(vars[0]); if(item.type==='create_pages'||!item.html.includes('Objectif général du parcours')||!item.html.includes('data-list-item-id')||item.chapo===item.html) throw Error('html/item'); const payload=buildCreatePagesPayload(); if(payload.type!=='create_pages'||payload.items.length!==1||payload.items[0].html!==item.html) throw Error('payload'); const checks=creationChecks(); if(checks.errors.length) throw Error('checks '+JSON.stringify(checks.errors)); ws.creation.drupal.defaultDates.unpublishDate='01/01/2026'; if(!creationChecks().errors.some(e=>/antérieure/.test(e.message))) throw Error('date check'); saveWorkspace(ws); const copy=importWorkspace(exportWorkspace(ws)); if(!copy.creation.associations[p.canonicalId].locked) throw Error('persist creation'); console.log('ok creation'); })();`, sandbox);
